// config.h - generated by premake
// do not edit by hand, instead edit config.lua and regenerate

#define CEGUI_LOAD_MODULE_DEBUG_SUFFIX "_d"
#define CEGUI_LOAD_MODULE_APPEND_SUFFIX_FOR_DEBUG 1
#define CEGUI_SAMPLES_USE_OPENGL 
#define CEGUI_SAMPLES_USE_IRRLICHT 
#define CEGUI_DEFAULT_XMLPARSER ExpatParser
#define CEGUI_SAMPLES_USE_DIRECTX_9 
#define CEGUI_DEFAULT_IMAGE_CODEC SILLYImageCodec
