// config.h - generated by premake
// do not edit by hand, instead edit config.lua and regenerate
// it is important that you use premake recreate this file if changing xml parsers or codecs for the static builds
#define CEGUI_CODEC_SILLY 1
#define CEGUI_DEFAULT_IMAGE_CODEC SILLYImageCodec
#define CEGUI_LOAD_MODULE_DEBUG_SUFFIX "_d"
#define CEGUI_LOAD_MODULE_APPEND_SUFFIX_FOR_DEBUG 1
#define CEGUI_FALAGARD_RENDERER 
#define CEGUI_WITH_TINYXML 1
#define CEGUI_DEFAULT_XMLPARSER TinyXMLParser
#define CEGUI_LUA_VER 50
